proxy_address: http://192.168.90.1:8080

local:
  api_address: http://localhost:8001

development:
  api_address: http://134.94.117.112:8000

production:
  api_address: https://ethos-builda.fz-juelich.de

base_url: /api/v8_20240916/

nominatim:
  host: 134.94.117.112
  port: 8080
