proxy:
  host: 192.168.90.1
  port: 8080

dev:
  api:
    host: localhost
    port: 8000

staging:
  api:
    host: iek3360.iek.kfa-juelich.de
    port: 8000

base_url: /api/v0/

nominatim:
  host: iek3360.iek.kfa-juelich.de
  port: 8080
