proxy:
  host: 192.168.90.1
  port: 8080

dev:
  api:
    host: localhost
    port: 8001

staging:
  api:
    host: 134.94.117.112
    port: 8000

base_url: /api/v0/

nominatim:
  host: 134.94.117.112
  port: 8080
